# fly.toml app configuration file generated for parrotbot on 2023-07-07T22:11:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "parrotbot"
primary_region = "eze"

[build]
  builder = "paketobuildpacks/builder:base"
